# Generated by Django 4.0.2 on 2022-03-08 19:47

import django.core.files.storage
from django.db import migrations, models
import utils.uploadjobimg


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/Django/JobScout/jobscout/media/'), upload_to=utils.uploadjobimg.upload_job_img),
        ),
    ]
