# Generated by Django 4.0.3 on 2022-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_alter_jobcard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
