# Generated by Django 4.0.2 on 2022-03-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0005_jobcard_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='category',
            new_name='company',
        ),
    ]
