# Generated by Django 4.0.2 on 2022-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0006_rename_category_jobcard_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
