# Generated by Django 4.0.2 on 2022-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0007_jobcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
