# Generated by Django 4.0.3 on 2022-03-11 21:58

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.uploadimg


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0008_alter_jobcard_deadline_alter_jobcard_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/Django/jobscout/media/'), upload_to=utils.uploadimg.upload_job_img),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='joblist.jobcategory'),
        ),
    ]
