# Generated by Django 4.0.3 on 2022-03-15 19:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0010_remove_jobcard_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/Django/jobscout/media/blog_media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
