# Generated by Django 4.0.3 on 2022-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0010_remove_jobcard_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
