# Generated by Django 4.0.3 on 2022-03-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0011_alter_jobcard_logo_alter_jobcard_slug'),
        ('joblist', '0011_alter_jobcard_options_alter_jobcard_slug'),
    ]

    operations = [
    ]
