# Generated by Django 4.0.3 on 2022-03-20 13:33

from django.db import migrations, models
import utils.uploadimg


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0014_alter_jobcard_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.uploadimg.upload_job_img),
        ),
    ]
