# Generated by Django 4.0.2 on 2022-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
