# Generated by Django 4.0.3 on 2022-03-20 16:31

from django.db import migrations, models
import utils.uploadimg


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.uploadimg.upload_contact_file),
        ),
    ]
