# Generated by Django 4.0.2 on 2022-03-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
