# Generated by Django 4.0.3 on 2022-03-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0005_about_services_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
