# Generated by Django 4.0.3 on 2022-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0007_alter_about_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
