# Generated by Django 4.0.3 on 2022-03-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_little_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleFile',
        ),
    ]
