# Generated by Django 4.0.3 on 2022-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_articlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
