# Generated by Django 4.0.3 on 2022-03-11 21:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_slug_articlefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/sevilledev/Desktop/Django/jobscout/media/blog_media'), upload_to=''),
        ),
    ]
