# Generated by Django 4.0.3 on 2022-03-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_date_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default='14.03.2022 12:57:21'),
        ),
    ]
