# Generated by Django 4.0.3 on 2022-03-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_slug_alter_articlefile_file'),
        ('blog', '0017_alter_article_options'),
    ]

    operations = [
    ]
