# Generated by Django 4.0.2 on 2022-03-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0002_alter_jobcard_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCard',
        ),
    ]
